### ISSUE TITLE
请问怎么绘制报告图

### ISSUE THREAD

**Issue by ws1227** [YOrange834/HealthChartView#2]
如下图链接所示的报告怎么绘制呢 有什么意见吗
https://raw.githubusercontent.com/reubn/ecg/master/readme/0.png

**Comment by YOrange834** [comment]
Demo里面有个ECG Report就是专门绘制心电图报告的，可以参考一下里面的例子，之所以没做成cocoapds 安装方式是因为这种图标订制程度太高，不太好封装。

**Comment by ws1227** [comment]
方便加下好友吗，我看了心电图报告部分，用了自己产品的数据，生成的线条基本是个水平的，看了源码有很多不理解的参数，修改后还是没实现设定的效果。
我的微信号是wangsen_weixin
